### ISSUE TITLE
Border radius issue

### ISSUE THREAD

**Issue by amandapennell** [amandapennell/first-website#1]
The *image border* needs to appear more **circular**  📷 

@

```css
img {
    border-radius: 8px;
}
```
https://github.com/amandapennell/first-website/blob/css-borders/styles.css#L2-L5

![lana-snowden](https://user-images.githubusercontent.com/31744744/30720994-e1d9322e-9ef7-11e7-86f9-9cdeb8b805c6.JPG)
